name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t mikecappeller/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true mikecappeller/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-368623

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-east1-b

      - name: Build
        run: |-
          docker build -t mikecappeller/multi-client-k8s-gh:latest -t mikecappeller/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t mikecappeller/multi-server-k8s-pgfix-gh:latest -t mikecappeller/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t mikecappeller/multi-worker-k8s-gh:latest -t mikecappeller/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push mikecappeller/multi-client-k8s-gh:latest
          docker push mikecappeller/multi-server-k8s-pgfix-gh:latest
          docker push mikecappeller/multi-worker-k8s-gh:latest

          docker push mikecappeller/multi-client-k8s-gh:${{ env.SHA }}
          docker push mikecappeller/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push mikecappeller/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=mikecappeller/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=mikecappeller/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=mikecappeller/multi-worker-k8s-gh:${{ env.SHA }}
